 "use client";
import {useEffect,useState} from"react";
export default function AdminPage(){
 const[auth,setAuth]=useState("checking"),[password,setPassword]=useState(""),[email,setEmail]=useState(""),[users,setUsers]=useState([]),[selected,setSelected]=useState(null),[rating,setRating]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{fetch("/api/admin/session",{cache:"no-store"}).then(r=>r.json()).then(x=>setAuth(x.authenticated?"ready":"login")).catch(()=>setAuth("login"))},[]);
 async function login(e){e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/admin/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password})}),j=await r.json();if(!r.ok)throw Error(j.error);setPassword("");setAuth("ready")}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function search(){setBusy(true);setError("");setSelected(null);try{const r=await fetch(`/api/admin/users/search?email=${encodeURIComponent(email.trim())}`),j=await r.json();if(!r.ok)throw Error(j.error);setUsers(j.users||[]);if(!j.users?.length)setError("No user found.")}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function openUser(uid){setBusy(true);setError("");try{const r=await fetch(`/api/admin/users/${uid}`),j=await r.json();if(!r.ok)throw Error(j.error);setSelected(j);setRating(j.override?.enabled?String(j.override.overallRating):"")}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function save(){if(!selected)return;setBusy(true);setError("");try{const r=await fetch(`/api/admin/users/${selected.user.uid}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({overallRating:rating})}),j=await r.json();if(!r.ok)throw Error(j.error);await openUser(selected.user.uid)}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function remove(){if(!selected||!confirm("Remove custom result?"))return;setBusy(true);try{await fetch(`/api/admin/users/${selected.user.uid}`,{method:"DELETE"});await openUser(selected.user.uid)}finally{setBusy(false)}}
 async function logout(){await fetch("/api/admin/logout",{method:"POST"});setAuth("login");setSelected(null)}
 if(auth==="checking")return <div className="glass p-8 max-w-md mx-auto mt-12 text-center">Checking admin session…</div>;
 if(auth==="login")return <div className="max-w-md mx-auto mt-12"><form onSubmit={login} className="glass p-6 sm:p-8 space-y-4"><div><p className="eyebrow">LUMINA</p><h1 className="text-3xl font-black mt-1">Admin</h1><p className="text-sm text-white/40 mt-2">Personal project controls.</p></div><input required type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Admin password" className="field"/><button disabled={busy} className="btn-neon w-full">{busy?"Checking…":"Enter admin panel"}</button>{error&&<p className="error-box">{error}</p>}</form></div>;
 return <div className="max-w-6xl mx-auto space-y-5 pb-12"><div className="glass p-5 sm:p-7 flex items-center justify-between"><div><p className="eyebrow">PERSONAL CONTROL PANEL</p><h1 className="text-3xl font-black mt-1">LUMINA Admin</h1><p className="text-sm text-white/40 mt-2">Custom demo results for friends.</p></div><button onClick={logout} className="text-sm text-white/45">Logout</button></div>
 <div className="glass p-5 sm:p-6"><div className="flex gap-2"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} onKeyDown={e=>e.key==="Enter"&&search()} placeholder="Search by email" className="field flex-1"/><button onClick={search} disabled={busy} className="btn-neon px-5">Search</button></div>{users.map(u=><button key={u.uid} onClick={()=>openUser(u.uid)} className="w-full text-left mt-2 rounded-xl border border-white/[.07] bg-black/20 p-4"><b>{u.name||"Unnamed user"}</b><span className="text-white/40 ml-2">{u.email}</span>{u.username&&<span className="text-white/30 ml-2">@{u.username}</span>}</button>)}{error&&<p className="error-box mt-4">{error}</p>}</div>
 {selected&&<div className="grid lg:grid-cols-[.8fr_1.2fr] gap-5"><section className="glass p-5 sm:p-6"><p className="eyebrow">USER</p><h2 className="text-xl font-bold mt-1">{selected.user.name||"Unnamed"}</h2><p className="text-sm text-white/45 mt-1 break-all">{selected.user.email}</p><p className="text-sm text-white/35 mt-1">@{selected.user.username||"—"}</p><div className="mt-5 rounded-xl bg-black/20 border border-white/5 p-4"><p className="text-xs text-white/35 uppercase">Saved scans</p><p className="text-2xl font-black mt-1">{selected.history?.length||0}</p></div><div className="mt-3 rounded-xl bg-black/20 border border-white/5 p-4"><p className="text-xs text-white/35 uppercase">Custom result</p><p className="font-bold mt-1">{selected.override?.enabled?`${selected.override.overallRating}/10 · active`:"None"}</p></div></section>
 <section className="glass p-5 sm:p-6"><p className="eyebrow">CUSTOM RESULT</p><h2 className="text-2xl font-black mt-1">Set a demo rating</h2><p className="text-sm text-white/40 mt-2">The displayed metrics update consistently from this rating.</p><div className="flex gap-2 mt-5 max-w-sm"><input type="number" min="1" max="10" step=".1" value={rating} onChange={e=>setRating(e.target.value)} placeholder="8.7" className="field"/><button onClick={save} disabled={busy} className="btn-neon">Save</button></div>{selected.override?.enabled&&<button onClick={remove} disabled={busy} className="text-sm text-rose-300/70 mt-4">Remove custom result</button>}<p className="eyebrow mt-7">RECENT HISTORY</p><div className="mt-3 space-y-2 max-h-80 overflow-auto">{(selected.history||[]).map(x=><div key={x.id} className="rounded-xl border border-white/5 bg-black/20 p-3 flex justify-between text-sm"><span className="text-white/40">{x.ts?new Date(x.ts).toLocaleString():"—"}</span><b>{x.numeric}/10 · {x.tier}</b></div>)}</div></section></div>}</div>
}