// Common country calling codes for the registration phone field.
// India is first in the list so it is the natural default selection.
export const COUNTRY_CODES = [
  { name: "India", dial: "+91" },
  { name: "United States", dial: "+1" },
  { name: "Canada", dial: "+1" },
  { name: "United Kingdom", dial: "+44" },
  { name: "United Arab Emirates", dial: "+971" },
  { name: "Saudi Arabia", dial: "+966" },
  { name: "Qatar", dial: "+974" },
  { name: "Bahrain", dial: "+973" },
  { name: "Kuwait", dial: "+965" },
  { name: "Oman", dial: "+968" },
  { name: "Pakistan", dial: "+92" },
  { name: "Bangladesh", dial: "+880" },
  { name: "Sri Lanka", dial: "+94" },
  { name: "Nepal", dial: "+977" },
  { name: "Bhutan", dial: "+975" },
  { name: "Maldives", dial: "+960" },
  { name: "Singapore", dial: "+65" },
  { name: "Malaysia", dial: "+60" },
  { name: "Thailand", dial: "+66" },
  { name: "Indonesia", dial: "+62" },
  { name: "Philippines", dial: "+63" },
  { name: "Vietnam", dial: "+84" },
  { name: "Myanmar", dial: "+95" },
  { name: "Cambodia", dial: "+855" },
  { name: "Laos", dial: "+856" },
  { name: "China", dial: "+86" },
  { name: "Japan", dial: "+81" },
  { name: "South Korea", dial: "+82" },
  { name: "Hong Kong", dial: "+852" },
  { name: "Taiwan", dial: "+886" },
  { name: "Australia", dial: "+61" },
  { name: "New Zealand", dial: "+64" },
  { name: "Russia", dial: "+7" },
  { name: "Germany", dial: "+49" },
  { name: "France", dial: "+33" },
  { name: "Italy", dial: "+39" },
  { name: "Spain", dial: "+34" },
  { name: "Netherlands", dial: "+31" },
  { name: "Belgium", dial: "+32" },
  { name: "Switzerland", dial: "+41" },
  { name: "Austria", dial: "+43" },
  { name: "Sweden", dial: "+46" },
  { name: "Norway", dial: "+47" },
  { name: "Denmark", dial: "+45" },
  { name: "Finland", dial: "+358" },
  { name: "Ireland", dial: "+353" },
  { name: "Portugal", dial: "+351" },
  { name: "Greece", dial: "+30" },
  { name: "Poland", dial: "+48" },
  { name: "Czech Republic", dial: "+420" },
  { name: "Hungary", dial: "+36" },
  { name: "Romania", dial: "+40" },
  { name: "Ukraine", dial: "+380" },
  { name: "Turkey", dial: "+90" },
  { name: "Israel", dial: "+972" },
  { name: "Egypt", dial: "+20" },
  { name: "South Africa", dial: "+27" },
  { name: "Nigeria", dial: "+234" },
  { name: "Kenya", dial: "+254" },
  { name: "Ghana", dial: "+233" },
  { name: "Tanzania", dial: "+255" },
  { name: "Uganda", dial: "+256" },
  { name: "Morocco", dial: "+212" },
  { name: "Tunisia", dial: "+216" },
  { name: "Algeria", dial: "+213" },
  { name: "Mexico", dial: "+52" },
  { name: "Brazil", dial: "+55" },
  { name: "Argentina", dial: "+54" },
  { name: "Chile", dial: "+56" },
  { name: "Colombia", dial: "+57" },
  { name: "Peru", dial: "+51" },
  { name: "Venezuela", dial: "+58" },
  { name: "Ecuador", dial: "+593" },
  { name: "Uruguay", dial: "+598" },
  { name: "Bolivia", dial: "+591" },
  { name: "Paraguay", dial: "+595" },
];
