"use client";
import {signInWithEmailAndPassword} from "firebase/auth";
import {auth} from "@/lib/firebase";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import Link from "next/link";
import B from "@/components/GoogleButton";
import GuestGate from "@/components/GuestGate";
export default function Login(){const[email,setEmail]=useState(""),[pass,setPass]=useState(""),[err,setErr]=useState(""),[busy,setBusy]=useState(false);const r=useRouter();const submit=async e=>{e.preventDefault();if(busy)return;setBusy(true);setErr("");try{await signInWithEmailAndPassword(auth,email.trim(),pass);r.replace("/dashboard/upload");r.refresh()}catch(x){const code=x?.code||"";setErr(code.includes("invalid-credential")?"Email or password is incorrect.":code.includes("too-many")?"Too many attempts. Try again later.":x?.message?.replace("Firebase: ","")||"Login failed.")}finally{setBusy(false)}};return <GuestGate><div className="max-w-md mx-auto mt-8 sm:mt-14"><form onSubmit={submit} className="glass p-6 sm:p-8 space-y-4"><div><p className="eyebrow">WELCOME BACK</p><h1 className="text-3xl font-black mt-1">Log in</h1><p className="text-sm text-white/45 mt-2">Continue to your LUMINA dashboard.</p></div><input required type="email" autoComplete="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} className="field"/><input required type="password" autoComplete="current-password" placeholder="Password" value={pass} onChange={e=>setPass(e.target.value)} className="field"/><button disabled={busy} className="btn-neon w-full">{busy?"Signing in…":"Log in"}</button>{err&&<p className="error-box">{err}</p>}<div className="divider"><span>or</span></div><B/><p className="text-center text-sm text-white/45">New here? <Link href="/register" className="text-cyan-300">Create an account</Link></p></form></div></GuestGate>}
