"use client";
import {createUserWithEmailAndPassword,updateProfile,deleteUser} from "firebase/auth";
import {auth,db} from "@/lib/firebase";
import {doc,setDoc} from "firebase/firestore";
import {useState} from "react";
import {useRouter} from "next/navigation";
import Link from "next/link";
import GuestGate from "@/components/GuestGate";
import ResearchConsent from "@/components/ResearchConsent";
import {COUNTRY_CODES} from "@/lib/countryCodes";
export default function Register(){const[f,setF]=useState({name:"",username:"",email:"",pass:"",phone:"",countryCode:"+91"}),[err,setErr]=useState(""),[busy,setBusy]=useState(false),[consent,setConsent]=useState(true);const r=useRouter();const change=(k,v)=>setF(x=>({...x,[k]:v}));const submit=async e=>{e.preventDefault();if(busy)return;if(!consent){setErr("Please check the box to agree to our Privacy Policy & Terms before continuing.");return}setBusy(true);setErr("");try{const c=await createUserWithEmailAndPassword(auth,f.email.trim(),f.pass);await updateProfile(c.user,{displayName:f.name.trim()});try{await setDoc(doc(db,"users",c.user.uid),{name:f.name.trim(),username:f.username.trim(),email:f.email.trim(),countryCode:f.countryCode,phone:f.phone.trim(),createdAt:Date.now()},{merge:true})}catch(profileError){try{await deleteUser(c.user)}catch{}throw profileError}r.replace("/dashboard/upload")}catch(x){const code=x?.code||"";setErr(code.includes("email-already")?"An account already exists for this email.":code.includes("weak-password")?"Use a stronger password (at least 6 characters).":x?.message?.replace("Firebase: ","")||"Registration failed")}finally{setBusy(false)}};return <GuestGate><div className="max-w-md mx-auto mt-8 sm:mt-12"><form onSubmit={submit} className="glass p-6 sm:p-8 space-y-4"><div><p className="eyebrow">GET STARTED</p><h1 className="text-3xl font-black mt-1">Create account</h1><p className="text-sm text-white/45 mt-2">Your analyses stay tied to your account.</p></div><input required autoComplete="name" placeholder="Full name" value={f.name} onChange={e=>change("name",e.target.value)} className="field"/><input required autoComplete="username" placeholder="Username" value={f.username} onChange={e=>change("username",e.target.value)} className="field"/><input required type="email" autoComplete="email" placeholder="Email" value={f.email} onChange={e=>change("email",e.target.value)} className="field"/><div className="field-row"><select value={f.countryCode} onChange={e=>change("countryCode",e.target.value)} className="field">{COUNTRY_CODES.map(c=><option key={c.name} value={c.dial}>{c.name} ({c.dial})</option>)}</select><input required type="tel" inputMode="tel" autoComplete="tel" placeholder="Phone number" pattern="[0-9]{6,14}" value={f.phone} onChange={e=>change("phone",e.target.value)} className="field"/></div><input required minLength={6} type="password" autoComplete="new-password" placeholder="Password (6+ chars)" value={f.pass} onChange={e=>change("pass",e.target.value)} className="field"/><button disabled={busy} className="btn-neon w-full">{busy?"Creating…":"Create account"}</button><ResearchConsent identityKey={f.email} onChange={setConsent}/>{err&&<p className="error-box">{err}</p>}<p className="text-center text-sm text-white/45">Already have an account? <Link href="/login" className="text-cyan-300">Log in</Link></p></form></div></GuestGate>}
